name: Build, lint

on: [ push, pull_request ]

jobs:
  build-lint:
    name: Build & lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: npm ci
      - name: Build
        run: npm run add-declarations
      - name: Check if type declarations are up-to-date
        run: |
          git diff --exit-code --color -- ./**/*.d.ts
      - name: Lint
        run: npm run lint
